lovers_lock_cadenas:
    resource: "@LoversLockCadenasBundle/Controller/"
    type:     annotation
    prefix:   /

pont:
    path:   /
    defaults:  { _controller: LoversLockPontBundle:Default:index }

admin:
    path:   /admin
    defaults:  { _controller: LoversLockUtilisateurBundle:Default:admin }

utlisateur:
    resource: "@LoversLockUtilisateurBundle/Resources/config/routing.yml"
    prefix:   /utilisateur

#HWIOAuthBundle routes

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login
    defaults:  { _controller: LoversLockCadenasBundle:Default:index }
hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

facebook_login:
    pattern: /login/check-facebook
    defaults:  { _controller: LoversLockPontBundle:Default:index }
    #defaults:  { _controller: LoversLockCadenasBundle:Default:index }


